### PR TITLE
7.x Symfony 6 support

### PR DESCRIPTION
**Pull request by joanna-bak-sourceability**

### CODE REVIEW

**Comment by joanna-bak-sourceability** [comment]
@alexander-schranz can this be merged?

**Comment by alexander-schranz** [comment]
Would first need to have a deeper look and review of the changes. But it seems the tests are not started, can you check why this is happening? Maybe something wrong in the adopted workflow file?

**Comment by joanna-bak-sourceability** [comment]
I pushed an empty commit to restart the worflow.
https://github.com/handcraftedinthealps/ElasticsearchDSL/actions/runs/2676728553
Workflow awaits your approval

**Comment by joanna-bak-sourceability** [comment]
It looks like below php 8.0 it does not work. 
Is it possible to require at least php 8? and deprecate all other versions?
We already run this fix on our project with php 8.1 and symfony 5.4

**Comment by alexander-schranz** [comment]
Dropping PHP 7 is fine for me still Symfony 3.4 and 4.4 should be kept 2.8 only if work it out of the box.

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@joanna-bak-sourceability @niklasnatter Thank you!

**Pull request merged**
